In [55]:
import pandas as pd

In [56]:
import matplotlib.pyplot as plt

In [57]:
telecom=pd.read_csv("telecom_churn (1).csv")
telecom

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

In [58]:
telecom.shape

(3333, 21)

In [59]:
telecom.info()

<class 'pandas.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3333 non-null   str
 1   account length          3333 non-null   int64
 2   area code               3333 non-null   int64
 3   phone number            3333 non-null   str
 4   international plan      3333 non-null   str
 5   voice mail plan         3333 non-null   str
 6   number vmail messages   3333 non-null   int64
 7   total day minutes       3333 non-null   float64
 8   total day calls         3333 non-null   int64
 9   total day charge        3333 non-null   float64
 10  total eve minutes       3333 non-null   float64
 11  total eve calls         3333 non-null   int64
 12  total eve charge        3333 non-null   float64
 13  total night minutes     3333 non-null   float64
 14  total night calls       3333 non-null   int64
 15  total night charge      3333 non-null   float64
 16  total intl minutes      3333 non-null   float64
 17  total intl calls        3333 non-null   int64
 18  total intl charge       3333 non-null   float64
 19  customer service calls  3333 non-null   int64
 20  churn                   3333 non-null   bool
dtypes: bool(1), float64(8), int64(8), str(4)
memory usage: 524.2 KB

In [60]:
telecom.isnull().sum()

state                     0
account length            0
area code                 0
phone number              0
international plan        0
voice mail plan           0
number vmail messages     0
total day minutes         0
total day calls           0
total day charge          0
total eve minutes         0
total eve calls           0
total eve charge          0
total night minutes       0
total night calls         0
total night charge        0
total intl minutes        0
total intl calls          0
total intl charge         0
customer service calls    0
churn                     0
dtype: int64

In [61]:
telecom.duplicated().any()

np.False_

In [62]:
telecom["one day minutes"]=telecom["total day minutes"]+telecom["total eve minutes"]+telecom["total night minutes"]+telecom["total intl minutes"]
telecom["percentage of minutes"]=telecom["one day minutes"]/telecom["one day minutes"].sum()*100

In [69]:
telecom["one day charge"]=telecom["total day charge"]+telecom["total eve charge"]+telecom["total night charge"]+telecom["total intl charge"]

In [70]:
telecom["percentage of charge"]=telecom["one day charge"]/telecom["one day charge"].sum()*100

In [71]:
telecom["one day calls"]=telecom["total day calls"]+telecom["total eve calls"]+telecom["total night calls"]+telecom["total intl calls"]

In [72]:
telecom["percentage of calls"]=telecom["one day calls"]/telecom["one day calls"].sum()*100

In [73]:
telecom

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total intl calls,total intl charge,customer service calls,churn,one day minutes,percentage of minutes,one day charge,percentage of charge,one day calls,percentage of calls
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,3,2.70,1,False,717.2,0.036357,75.56,0.038133,303,0.029793
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,3,3.70,1,False,625.2,0.031693,59.24,0.029897,332,0.032644
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,5,3.29,0,False,539.4,0.027343,62.29,0.031436,333,0.032743
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,7,1.78,2,False,564.8,0.028631,66.80,0.033713,255,0.025073
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,3,2.73,3,False,512.0,0.025954,52.09,0.026289,359,0.035299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,6,2.67,2,False,660.7,0.033492,60.10,0.030331,292,0.028711
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,4,2.59,3,False,585.4,0.029675,63.53,0.032062,239,0.023500
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,6,3.81,2,False,675.6,0.034248,67.74,0.034187,264,0.025958
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,10,1.35,2,False,517.6,0.026238,57.53,0.029034,336,0.033038
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,4,3.70,0,False,755.4,0.038293,77.01,0.038865,276,0.027138

In [75]:
telecom.to_csv('telecom.csv')